Enable snapshot tests.
Signed-off-by: Caroline Russell <caroline@appthreat.dev>

diff --git a/.github/workflows/snapshot_tests.yml b/.github/workflows/snapshot_tests.yml
--- a/.github/workflows/snapshot_tests.yml
+++ b/.github/workflows/snapshot_tests.yml
@@ -2,7 +2,12 @@ name: Generate Depscan Snapshots
 
 on:
   workflow_dispatch:
-
+  pull_request:
+    branches:
+      - master
+  push:
+    branches:
+      - master
 
 concurrency:
   group: "${{ github.workflow }}-${{ github.head_ref || github.run_id }}"
@@ -32,18 +37,24 @@ jobs:
 
       - name: Get boms
         run: |
-           git clone https://github.com/appthreat/cdxgen-samples.git /home/runner/work/cdxgen-samples
-           cd /home/runner/work/cdxgen-samples
+           git clone https://github.com/appthreat/cdxgen-samples.git /home/runner/work/new_snapshots
+           cd /home/runner/work/new_snapshots
            git checkout b5dc7d02548bc8f8983d981dc21de5612e37731c
+
+      - name: Get original snapshots
+        run: |
+          git clone https://github.com/AppThreat/dep-scan-snapshots.git /home/runner/work/original_snapshots
 
       - name: Generate snapshots and test
         env:
           DEPSCAN_CSAF_TEMPLATE: "/home/runner/work/dep-scan/dep-scan/contrib/csaf.toml"
           INPUT_THANK_YOU: "I have sponsored OWASP-dep-scan."
         run: |
-          mkdir /home/runner/work/new_snapshots
           source venv/bin/activate
           /home/runner/work/dep-scan/dep-scan/test/snapshots.py
+          if test -f /home/runner/work/new_snapshots/diffs.json; then
+            echo "status=FAILED" >> "$GITHUB_ENV"
+          fi
 
       - name: Upload artifacts
         uses: actions/upload-artifact@v4
@@ -51,3 +62,10 @@ jobs:
           path: |
             /home/runner/work/cdxgen-samples/*.vdr.json
             /home/runner/work/cdxgen-samples/*.csaf_v1.json
+            /home/runner/work/new_snapshots/diffs.json
+            /home/runner/work/new_snapshots/*.html
+
+
+      - name: Exit with error
+        if: ${{ env.status == 'FAILED' }}
+        run: exit 1
